#ifndef TERRAIN_H
#define TERRAIN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "evo.h"

COMPONENT(app_terrain, tv_component)
	/* the model renderer component that will render the terrain */
	tv_model_renderer *renderer;
	/* the model that holds all the tile types (generated by component). */
	tv_model *model;
ENDCOMPONENT(app_terrain)

#ifdef __cplusplus
}
#endif
#endif